### ISSUE TITLE
OS X Terminal.app port

### ISSUE THREAD

**Issue by ghost** [DanielPintilei/Cake#1]
It would be awesome to have a port for the default terminal application that ships with OS X.

**Comment by gnikyt** [comment]
Second this. I have an odd colorblindness where green is brown to me. Its extremely hard to find syntax themes which don't use green. This color scheme has been great to me, I'd love to see this ported into a terminal profile as well.

@brielov If I get some free time next week I'll try to work on a profile to export, ill see if it works out.
