### ISSUE TITLE
Complimentary UI theme for Cake?

### ISSUE THREAD

**Issue by ghost** [DanielPintilei/Cake#2]
Is there a suggested UI theme that goes well with Cake? Specifically for Atom?

**Comment by DanielPintilei** [comment]
Good question :grey_exclamation:

**Comment by fernandofleury** [comment]
I would like to know one as well. Usually I go with one dark/light, but for this one around I think we need something more brownish.

**Comment by bakana808** [comment]
personally, i recommend [`atom-material-ui`](https://atom.io/themes/atom-material-ui).

![](http://i.imgur.com/ctPL19g.png)

**Comment by toddmbloom** [comment]
Thanks! I'm actually using Atom Material but perhaps I just have too light a colour for it. I'll try out some different things (I'm using purple accents but I'll try pink ones). Did you customise the stylesheet at all?

**Comment by DanielPintilei** [comment]
A quick hack for atom-material-ui users that overrides the theme's git colors from the tree-view:
https://gist.github.com/DanielPintilei/d464b88a066e5167bc7fe412dcce4550
